{
    "event_id": "401000000",
    "teams": {
        "home": {
            "id": "2",
            "name": "Boston Celtics",
            "abbreviation": "BOS",
            "score": 83,
        },
        "away": {
            "id": "18",
            "name": "New York Knicks",
            "abbreviation": "NY",
            "score": 78,
        },
    },
    "game_status": {
        "state": "in",
        "description": "In Progress",
        "detail": "9:25 - 4th Quarter",
        "completed": False,
        "period": 4,
        "clock": "9:25",
    },
    "live_projection": {
        "projected_home_score": 104,
        "projected_away_score": 98,
        "projected_total": 201.66,
        "projected_remaining_points": 40.66,
        "most_likely_score": {
            "home": 104,
            "away": 98,
            "total": 202,
        },
        "market_total_line": 203,
        "difference_vs_market": -1.34,
        "p_over": 0.434,
        "relationship_to_market": "below_market",
        "model_inputs": {
            "current_home_score": 83,
            "current_away_score": 78,
            "period": 4,
            "clock": "9:25",
            "recent_points": None,
            "recent_minutes": None,
            "home_fouls_period": None,
            "away_fouls_period": None,
            "is_playoffs": True,
        },
        "data_quality": {
            "status": "live",
            "warnings": [],
            "market_line_source": "auto_search",
            "selected_market_ticker": "KXNBA-CELNYK-TOTAL-203",
            "kalshi_live_data_available": True,
            "kalshi_game_stats_available": False,
            "recent_scoring_source": None,
        },
        "source_urls": {
            "espn_summary": "https://site.api.espn.com/apis/site/v2/sports/basketball/nba/summary?event=401000000",
            "kalshi_markets": "https://api.elections.kalshi.com/trade-api/v2/markets?limit=100&status=open&series_ticker=KXNBATOTAL",
            "kalshi_milestones": "https://api.elections.kalshi.com/trade-api/v2/milestones?limit=10&related_event_ticker=KXNBA-CELNYK&category=Sports",
            "kalshi_live_data": "https://api.elections.kalshi.com/trade-api/v2/live_data/milestone/ms-1",
        },
    },
}
